# Generated by Django 3.2.4 on 2021-07-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('professional_title', models.CharField(max_length=50)),
                ('city_of_residence', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(to='resume.Personal_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_details')),
            ],
        ),
        migrations.CreateModel(
            name='Employment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location_city', models.CharField(max_length=50)),
                ('company_location_country', models.CharField(max_length=50)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('responsibilities', models.TextField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_details')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('OND/HND', 'OND/HND'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctorate degree', 'Doctorate degree'), ('Phd', 'Phd')], max_length=20)),
                ('major', models.CharField(max_length=50)),
                ('institution', models.CharField(help_text='Enter your institution here, e.g University of Uyo, Uyo', max_length=100)),
                ('start_date', models.DateField(help_text='Enter the date you started school here')),
                ('end_date', models.DateField(help_text="Enter the date you finished / the date you're expected to finish")),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_details')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=100)),
                ('year_obtained', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resume.personal_details')),
            ],
        ),
    ]
