# Generated by Django 3.2.4 on 2021-07-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_personal_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
