# Generated by Django 3.2.4 on 2021-07-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_personal_details_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifications',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employment_history',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
